language: bash
sudo: required

services:
  - docker

env:
  global:
  - secure: eDoseCnyN4ggr4lLCRx6PKeG+llJF0jDcWDpuk0Sj1xqiWrGy2926Z4wjVuYTbfMX5MaWQhjBF031X3BX4tLE6lfCV3P9svj9adx3VRa9W8IBvN3Suf7QlADoVfhGDMhayuQWoIOhT+kHquhwa1COVIkA+P6iiixic3Q5aRY4kTF22QVthO6Rwup1NvP8Zo00+NN4nGSQEn9pZJ7Bq6fzuSmlJnFmqHu1/Y626dUCjXA2vspU/Do8+q5ars3H+VfOBynZZk96Vu26i7LzLVAu2q6B4rH8ai8s3hAgeaW3sXNx2VYZHHRH4So+RnISroVwsoGDQ/re08ZxnhQNhEU+V4fFV5waoUtoLn9Pf4YgP3y1v8BFbU+AwRfJhru6S4HT35VgZdsVBnbt+QGSQEgXReQJcMMIyL6tfZ4Ux/B8CteTwUK+q38fyRnlxy167I5CP6dP+4l+LKM6KueZnnWbJKeGGEUI22f8S8Aqc1A+DCkgO0txw4iZ6p6OR0+KJJHfzKp/fwlmUnLEIZ9Ok6hnA7QwC+2mYiKOcEOWMm2iRM4aZ+jrwn7287LHAe8stkQVvo3cMpo7Y9fdDbP+g8NHOMxnfxi9+vSAtaoFn5rKnk/xGBVngvTTxMhsdfORf7m3r6u6TDy9NgCK1AO+DEfr7jP0IFdueae71pKCluUQ3k=
  - secure: Pzw9dMoST1geT3tJxPm901C0FNzZbNXfU7tNQd3+DCNEc9viYQ6Io+QsEFRfCHonX6Pyv5YJRaImDp99KyRgcnBvcHQ2MXalD/+zy2Gg/tFfxDaZhDitxq0BkoTzSIqu+U0MEUiGQTt/Hwu9SHGReuyg2UomknMt01gBqRwjZq8E8Fh97mOdUtDbLcGngFF4ieorsqZEdo5WKEzdEaQeKRKveJCNUQHcg4lSPzgQIbBh/m50NZbTuhPx4vAq17PsPdsd9JKrgw0nvHi6sAjnA3s33It9nqTzSIRKaJMZUme3EA+DUq4Qw+r5Mo1Sl5DgglmChrnmSBWVIG6TDxX7L3XzxjJ9Dd59Y9TT8m+uaiOD7PAir7NMmRxNWyUbikVVGpRWaqmoVK7VuwAUZNQtfvqM/t7dUjCwJEjae8X6fKNFz8ZgQyP2zrALlNjOurU7f8p0/4Tt8GlQC5noizf7gs3Xlh/ucMGv0rg3pBP6dpHv8Xb18CJpfUsGJDjdDVzPSZK6GdbD6f4wT24uM6t2RYbDji2fByHJG95KmplpNFYl5Pwkic1emz54ssHAA5vKgRPx+hRXYPAHpZrDY/177RRTUSau7XGL9I848lR1/NgaQtaxbnre2axEQkt2N+XXKd83+LL12pE8Tp3TibQ/ohKWISP2Wzo/y7lpLnSoR0g=
  - secure: R0AAo9m6MEMxcFngBOXH5jUWZFXzAqWZOGLFskpq2cvsb3fNqhLX0q9pe0LLexKJXBk56zn/3JWqCRUHZ5egReAIdYt98qk6fYjRw12rXo5aeWL0HoJQPuHMk/juTXEclfM3HZeWvr3hhstrhLKi9p7QXqPT6ovhGCMSMFGIFxfG9ubFFWNmO4JKeLqSUN9alyXG5VYpqs52hHLCj6hi8hOfryCbLLHYS6ph5PeKxLkRfZvWK4gFzeDvkaWD+cfCx5BZwW5xy9ZczviY4jpowH61BWnzHKJDyl8cvYIqfusiYM6ejJS19ruZe0aFPSKyYeVhmfz9056C5RrIyo66GdXNleZXGizUdYGedtjd0syUwSj8q+T4Ov9GNWOR2HhFuf6PyzPb3Nv3pyjBJjJSf5oKcuCublojAsKTgMIW2dCnoF5KLss1Xn1sdKFAtMfEcvF5hekF0PxoBckIq7jTSNJswlEEW3QNNrGpGG7cpJ9cdvZVM9VbPrK7C5t1XtaMdB4zPD0nYyAobwZRDWWG9HmYUR3f6lBUqzdOplW+fuG3Nq4qieHlAtovD0LMF4RyCJt4zzA37g60SX9rWvL8LSVsoTywgk+crxDXHaWInYKkamyNvmxNnBNBUvZddt9Ne/UMH1JoRiUWODAiu1cAv1+jvzIgvijUtEqb7iKuO54=

before_script: 
script:
  - bash mock_test.sh
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/ubiquiti-docker
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - cd unifi-controller; docker build -t $REPO:$COMMIT .
  - docker tag -f $REPO:$COMMIT $REPO:$TAG
  - docker tag -f $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

after_success:
